{% set name = "deprecation" %}
{% set version = "2.0.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "cbe7d15006bc339709be5e02b14884ecc479639c1a3714a908de3a8ca13b5ca9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - packaging

test:
  imports:
    - deprecation

about:
  home: http://deprecation.readthedocs.io/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'A library to handle automated deprecations'
  dev_url: https://github.com/briancurtin/deprecation
  doc_url: http://deprecation.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - kmuehlbauer
