travis:
  secure:
    BINSTAR_TOKEN: yobCH4U/9TdpDl65jAUWPa1PkgEOfqIXnW+No/E4p9fGLuIi/aKxNgmYD8HTBfPNxxMGi2wt1tb7ud8KMi5H8NYigdqB6NSr59ZsIXCFtlgPXdJL/8VQAHUzr8lzC3vpy5wsB0t6tULSzKHr/RgrwwsKHif/A5MW7WMTVDqPgUxQjN5Cz0KTX7tIavUKr9lMfxZ0Ti3Eay05TCxPwe7013dmz7KV3yT2NPmXmM59JhVgaoer+r2zh2tBoVjrgVkwUpaxAAIP6cd8p4sjfSffSysR9BL82idFijd3T+HvGrJYymMZeSVh4C6GBhyoJPrixtSj72DguUlMBS3NC7id14BAfcHhjyVU6eS0k+jOANTQ4cmRrNSqZ4KgYoGZsSH51o1gcv22vsBXpa4rlVBR17SQIFLoyWY9WE63WEJJNXmthY/XBvMl3V02lNYPtPlFSo1ZSbjE1+kToVnPLebkyk8a6F1JVQXBLiTq8FwHfasMepU+uGIcldxH1Uhm6jwjTo3AYVZ4F4ZhwRbwCzb1dt/07vQuurxuXKMqIGF2kBmYEW3HCKQRhgffdf3bZg5JTHgO41/4ZbvULiciVct+RJiFmBlWPocgh1ddwrU65XvsOnh++9haGTBO8CMdqsfYqYxCTIxNWPWrY8fMDZujGRiGY4y8CVSReZti7TnFvKE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
